# Generated by Django 5.1.7 on 2025-03-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Race', 'Race'), ('Class', 'Class'), ('Background', 'Background')], max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
