# Generated by Django 5.1.7 on 2025-04-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteroption',
            name='category',
            field=models.CharField(choices=[('Race', 'Race'), ('Class', 'Class'), ('Background', 'Background'), ('Language', 'Language')], max_length=50),
        ),
    ]
