# Generated by Django 5.1.7 on 2025-07-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargenapp', '0003_alter_characteroption_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_score', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='characteroption',
            name='category',
            field=models.CharField(choices=[('Char Name', 'Char Name'), ('Race', 'Race'), ('Class', 'Class'), ('Background', 'Background'), ('Alignment', 'Alignment'), ('Language', 'Language')], max_length=50),
        ),
        migrations.CreateModel(
            name='SpecStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abilities', models.ManyToManyField(blank=True, to='chargenapp.ability')),
            ],
        ),
    ]
