# Generated by Django 5.1.7 on 2025-07-31 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chargenapp', '0004_ability_alter_characteroption_category_specstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteroption',
            name='category',
            field=models.CharField(choices=[('Char Name', 'Char Name'), ('Race', 'Race'), ('Class', 'Class'), ('Background', 'Background'), ('Alignment', 'Alignment'), ('Level', 'Level'), ('Sex', 'Sex'), ('Player Name', 'Player Name')], max_length=50),
        ),
    ]
